version: '3.8'
services:
  stats-server:
    build: stats-service
    container_name: ewm-stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=ewm_stats_service
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=iamroot
      - DB_HOST=stats-db
      - DB_PORT=5432

  stats-db:
    image: postgres:13.7-alpine
    container_name: ewm-stats-db
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewm_stats_service
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=iamroot

  ewm-service:
    build: main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - DB_NAME=ewm_main_service
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=iamroot
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - EWM_STATS_SERVICE_URL=http://stats-server:9090

  ewm-db:
    image: postgres:13.7-alpine
    container_name: ewm-main-db
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewm_main_service
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=iamroot
